apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-09-17T04:44:51Z"
  labels:
    app: nginx-deployment
  name: myservice
  namespace: default
  resourceVersion: "46075"
  uid: d8038489-edfa-487f-831f-868c39d0c2d8
spec:
  clusterIP: 10.96.77.88
  clusterIPs:
  - 10.96.77.88
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
